### ISSUE TITLE
Bank restorer issue

### ISSUE THREAD

**Issue by THExSOFAxKING** [DarthVan/StarCraft2-Bank-Restorer#3]
I've tried to use the swarm special forces Bank restorer and it corrupts my saves even if I only change one thing. 
I've followed the steps in the help section and get the same outcome.
Thank you for your time!  I love the layout of this program! Very clean!!

**Comment by THExSOFAxKING** [comment]
Indeed it does reset game stats after any change I do.
I use Firefox but I play starcraft 2 using the battle net client. And I'm in America, Colorado.

I'll try more things a little later today. I'm headed to work now tho.
I appreciate you prompt response!
Thank you again man

-curtis

-------- Original Message --------

**Comment by DarthVan** [comment]
By default, all Author IDs are for EU region:

![3](https://github.com/DarthVan/StarCraft2-Bank-Restorer/assets/5062893/bf3944c2-8164-4132-8a58-d245b03a6b56)

Did you tried to use this **1-S2-1-4330213** as Author ID? Its for NA.

**Comment by THExSOFAxKING** [comment]
I'm an idiot!
That was the problem!
Thank you again man I greatly appreciate you!!

-------- Original Message --------

**Comment by DarthVan** [comment]
Noice! Closing the issue)

**Comment by THExSOFAxKING** [comment]
Is there any more games you will be adding to this?
Thank you again!!

-------- Original Message --------
